---
language: node_js
sudo: false
install: skip

node_js:
  - 10

services:
  - docker

git:
  depth: 5
  quiet: true

cache:
  directories:
    - docker-cache
    - node_modules
    - .npm

before_script:
  - |
    filename=docker-cache/saved_images.tar
    if [[ -f "$filename" ]]; then docker load < "$filename"; fi
    mkdir -p docker-cache
    docker pull jdkato/vale:latest
    docker pull 18fgsa/html-proofer:latest
    docker save -o "$filename" jdkato/vale:latest 18fgsa/html-proofer:latest
  - npm install

script:
  - >
    docker run --rm -it -v "${PWD}:/docs:ro" -w /docs jdkato/vale:latest
    --sort
    --config /.vale.ini
    $(cat .valerc)
  - npm run validate-pkg
  - npm run lint-yml
  - >
    docker run -v "${PWD}:/site:ro" 18fgsa/html-proofer:latest
    --empty-alt-ignore
    --check-favicon
    --check-img-http
    --enforce-https
    --only-4xx
    --file-ignore "/node_modules/"
    /site
  - npm run lint-js
  - npm run stylelint-css
  - npm run prettier-code

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY
  keep_history: true
  on:
    branch: master
