---
name: DeployGhPages

on:
  push:
    branches:
      - redirection

jobs:
  deploy-ghpages:
    runs-on: ubuntu-latest
    name: Deploy to GH-Pages
    steps:
      - name: Source checkout
        uses: actions/checkout@v2

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
